### PR TITLE
Fix gateway block id

### LINKED ISSUE #154: `GatewayProvider.callContract` fails when using `blockTag` or `blockNumber`.
Constructed request is probably incorrect - blockHash is always used.

### PR DESCRIPTION
**Pull request by cptartur**
## Describe your changes

This PR fixes incorrect serialization of block id in gateway methods.

## Linked issues

Closes #154 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

File: lib/src/main/kotlin/com/swmansion/starknet/extensions/ToParam.kt [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package com.swmansion.starknet.extensions
+
+import com.swmansion.starknet.data.types.BlockId
+
+@JvmSynthetic
+internal fun BlockId.toParam(): Pair<String, String> = when (this) {
```
Comment (Solpatium) [inline lib/src/main/kotlin/com/swmansion/starknet/extensions/ToParam.kt:6]: This is only used in GatewayProvider, why not define it there as a helper function?

**Review by Solpatium — CHANGES_REQUESTED** [review]

File: lib/src/main/kotlin/com/swmansion/starknet/extensions/ToParam.kt (hunk 1 above)
Comment (cptartur) [reply lib/src/main/kotlin/com/swmansion/starknet/extensions/ToParam.kt:6]: It would complicate testing of this function. While generally we probably shouldn't need to tests internals like this, issue this PR is resolving is caused by us not covering these cases (because test e2e test are incomplete and because of devnet limitations).

**Review by Solpatium — APPROVED** [review]
