### PR TITLE
Fix `TypedData.toJsonString()`

### LINKED ISSUE #498: Incorrect TypedData#toJsonString output
### What happened

The `TypedData#toJsonString` output for the Type Data shown below is incorrect. The output is missing is missing `"type": "merkletree"` under `types.Session.AllowedMethods`. 

We noticed this issue for `merkletree` serialisation, but please verify also if `enum` doesn't have the same issue.

```json
{
  "types": {
    "StarknetDomain": [
      {
        "name": "name",
        "type": "shortstring"
      },
      {
        "name": "version",
        "type": "shortstring"
      },
      {
        "name": "chainId",
        "type": "shortstring"
      },
      {
        "name": "revision",
        "type": "shortstring"
      }
    ],
    "Allowed Method": [
      {
        "name": "Contract Address",
        "type": "ContractAddress"
      },
      {
        "name": "selector",
        "type": "selector"
      }
    ],
    "Session": [
      {
        "name": "Expires At",
        "type": "timestamp"
      },
      {
        "name": "Allowed Methods",
        "type": "merkletree",
        "contains": "Allowed Method"
      },
      {
        "name": "Metadata",
        "type": "string"
      },
      {
        "name": "Session Key",
        "type": "felt"
      }
    ]
  },
  "primaryType": "Session",
  "domain": {
    "name": "SessionAccount.session",
    "version": "0x31",
    "chainId": "0x534e5f5345504f4c4941",
    "revision": "1"
  },
  "message": {
    "Expires At": 1720704208,
    "Allowed Methods": [
      {
        "Contract Address": "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7",
        "selector": "transfer"
      }
    ],
    "Metadata": "{\"projectID\":\"test-dapp\",\"txFees\":[{\"tokenAddress\":\"0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7\",\"maxAmount\":\"100000000000000000\"}]}",
    "Session Key": "0x3f94fb0d79cba8507a8775dc4cd4328f91ba33d1a32cb54c8c28eef0e258fa3"
  }
}

```

### Stack trace

```
Input element does not contain mandatory field 'type'
java.lang.IllegalArgumentException: Input element does not contain mandatory field 'type'
	at com.swmansion.starknet.data.serializers.TypedDataTypeBaseSerializer.selectDeserializer(TypedDataTypeBaseSerializer.kt:19)
	at kotlinx.serialization.json.JsonContentPolymorphicSerializer.deserialize(JsonContentPolymorphicSerializer.kt:93)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111)
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at com.swmansion.starknet.data.TypedData$$serializer.deserialize(TypedData.kt:89)
	at com.swmansion.starknet.data.TypedData$$serializer.deserialize(TypedData.kt:89)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107)
	at com.swmansion.starknet.data.TypedData$Companion.fromJsonString(TypedData.kt:606)
```

### Steps to reproduce

```
val inputStr = ... //see json above
val typedData = TypedData.fromJsonString(typedData = inputStr)
val outputStr = typedData.toJsonString()
TypedData.fromJsonString(outputStr)
```

### SDK Version

0.12.1

### Language

Kotlin

### Language

n/a

### Language version

2.0.0

### What operating system are you using?

Mac

### Is there an existing issue for this?

- [X] I have searched the existing issues and verified no issue exits for this problem.

### PR DESCRIPTION
**Pull request by franciszekjob**
## Describe your changes

Fix `TypedData.toJsonString()` by adding `encodeDefaults` flag set to `true`.

Before: `type` field has been skipped while serializing `MerkleTreeType` and `EnumType`, because their value is default
After: `type` field is properly serialized

## Linked issues

Closes #498 

## Breaking changes

- [ ] This issue contains breaking changes

### CODE REVIEW

File: lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt [hunk 1]
```diff
@@ -186,6 +186,7 @@ data class TypedData private constructor(
             Json.decodeFromJsonElement<Revision>(it)
         } ?: Revision.V0
 
+        @Transient
```
Comment (franciszekjob) [inline lib/src/main/kotlin/com/swmansion/starknet/data/TypedData.kt:189]: This has been added to avoid including `separatorName` when serializing `Domain`.

**Review by ddoktorski — APPROVED** [review]
